spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/profile
    driver-class-name: org.mariadb.jdbc.Driver
    username: junhyeok
    password: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
